version: '3.9'
services:
  postgres-server:
    restart: always
    container_name: spring-postgres
    image: postgres:14
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=sifra123
      - POSTGRES_DB=test
  # APP**
  web:
    build: .
    container_name: spring-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-server:5432/test
    expose:
      - 8080
    ports:
      - 8080:8080